set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_ASM_FLAGS -m32)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_FLAGS -m32)
set(CMAKE_C_COMPILER_TARGET i386-none-elf)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Search host, redirect finds to oblivion
set(CMAKE_FIND_ROOT_PATH /dev/null)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FINDROOT_PATH_MODE_INCLUDE ONLY)
